services:
  db:
    image: postgres:15-alpine
    container_name: sir-postgres
    environment:
      POSTGRES_USER: sdi_user
      POSTGRES_PASSWORD: sdi_password
      POSTGRES_DB: safety_db
    ports:
      - "5432:5432"
    volumes:
      - sir_postgres_data:/var/lib/postgresql/data

volumes:
  sir_postgres_data:
